#!/usr/bin/env python3
"""graph-neighbors.py — edge-traversal helper for the knowledge graph (F-069 Step 5).

The ONE real traversal implementation shared by the locate-steps (SKILL.md
prose invokes it) and the tests — removing the sim-vs-real gap (plan Design
note 4). Deterministic: reads `edges:` frontmatter lists only; which neighbor
is USEFUL stays LLM judgment at the call site.

F-076: traversal is BIDIRECTIONAL and cross-domain. Edge-bearing nodes are
F features AND syn pages; a node reachable only through its INBOUND edges
(edges are written one-sided into the `from` node) is reached by a reverse
scan, displayed with the kind-inversion label from graph_common (supersedes
read backward reads superseded_by; documented_by reads documents). Reverse
edges are computed at READ time — never written into the target's frontmatter
(conclusion D5: no second source of truth).

Cost note: the reverse scan reads EVERY edge-bearing node per invocation —
O(corpus), not O(neighborhood). Fine at the current corpus scale; the
completion table carries the numeric revisit trigger (corpus > 500 nodes or
a batched call > 500ms) and the pre-decided escape (a derived inbound index
regenerated by graph-index-gen — a build artifact, not mirrored frontmatter).

Usage: graph-neighbors.py [--root DIR] [--synthesis-root DIR] [--hops N] <start-id> [...]
Output: one line per reached node: `<reached-id>\t<kind-label>\t<via-id>\t<evidence>`
  (kind-label is the edge kind read FROM the via node's side: forward edges
  print the stored kind, reverse-reached nodes print the inverse label).
Exit: 0 = ok (zero lines is a valid result) | 2 = usage (bad root / unknown start id).
"""
import argparse
import os
import re
import sys

import yaml

import graph_common

if __name__ != "__main__":
    raise SystemExit("graph-neighbors.py is subprocess-only; do not import")

parser = argparse.ArgumentParser()
parser.add_argument("--root", default=os.environ.get("FEATURES_ROOT", ".ae/features"))
parser.add_argument("--synthesis-root", default=None)
parser.add_argument("--hops", type=int, default=1)
parser.add_argument("starts", nargs="+")
try:
    args = parser.parse_args()
except SystemExit:
    sys.exit(2)

root = os.path.realpath(args.root)
if not os.path.isdir(root):
    print(f"[graph-neighbors] usage error: no such root: {args.root}", file=sys.stderr)
    sys.exit(2)
syn_root = os.path.realpath(args.synthesis_root) if args.synthesis_root \
    else graph_common.default_synthesis_root(root)

node_map, _ = graph_common.build_node_map(root, syn_root)

edges_by_id = {nid: graph_common.read_edges(path)
               for nid, (cls, path) in node_map.items() if cls in ("F", "syn")}

# reverse index, computed per invocation (never persisted) — the ONE shared
# construction in graph_common (index-gen renders from the same helper)
incoming_by_id = graph_common.build_inbound_index(node_map)

# a start id is legal if it is ANY known node — a node with only inbound
# edges (the F-069→F-072 gap class) must be a valid traversal origin
unknown = [s for s in args.starts if s not in node_map]
if unknown:
    print(f"[graph-neighbors] usage error: unknown (or unparseable — run graph-lint.py) start id(s): {', '.join(unknown)}", file=sys.stderr)
    sys.exit(2)

frontier, seen = list(args.starts), set(args.starts)
for _ in range(max(args.hops, 0)):
    next_frontier = []

    def reach(node, label, via, evidence):
        if node in seen:
            return
        seen.add(node)
        print(f"{node}\t{label}\t{via}\t{evidence}")
        # hop continuation: ANY known node can extend the walk — reverse
        # edges give nodes without outgoing edges a neighborhood too
        if node in node_map:
            next_frontier.append(node)

    for node_id in frontier:
        for edge in edges_by_id.get(node_id, []):
            if not isinstance(edge, dict):
                continue
            target = str(edge.get("id", ""))
            if target:
                reach(target, edge.get("kind", ""), node_id, edge.get("evidence", ""))
        for src, edge in incoming_by_id.get(node_id, []):
            kind = str(edge.get("kind", ""))
            reach(src, graph_common.INVERSE.get(kind, kind), node_id,
                  edge.get("evidence", ""))
    frontier = next_frontier
sys.exit(0)
